# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3f79959
_src_path: gh:scipp/copier_template
description: Diffraction data reduction for the European Spallation Source
max_python: '3.13'
min_python: '3.10'
namespace_package: ess
nightly_deps: scipp,scippnexus,sciline,plopp,scippneutron,essreduce,tof
orgname: scipp
prettyname: ESSdiffraction
projectname: essdiffraction
related_projects: Scipp,ScippNexus,ScippNeutron,Sciline,Plopp,ESSreduce
year: 2025
